In [33]:
import requests
import pandas as pd
from bs4 import BeautifulSoup as bs
import time
import numpy as np

In [34]:
url = "https://fds.career.vt.edu/Salary/Details?cohort=2019-2020&dispmajor=Y"
resp= requests.get(url)
soup = bs(resp.text)

In [44]:
data = []
for row in soup.select('tr'):
    row_text = [x.text for x in row.find_all('td')]
    data.append(row_text)
    print(', '.join(row_text))

 Whole University
,
                            6766
                        ,
                            2113
                        ,
                            31%
                        ,
                            1397
                        ,
                            66%
                        ,
                            1064
                        ,
                            76%
                        ,
$48500                        ,
$64000                        ,
$75000

College of Agriculture and Life Sciences
,
                            733
                        ,
                            154
                        ,
                            21%
                        ,
                            62
                        ,
                            40%
                        ,
                            39
                        ,
                            63%
                        ,
$29120                        ,
$38000                        ,
$46000

Agribusiness
,
                            42
                        ,
                            16
                        ,
                            38%
                        ,
                            10
                        ,
                            63%
                        ,
                            9
                        ,
                            90%
                        ,
,
$40000                        ,


Agricultural Sciences
,
                            16
                        ,
                            4
                        ,
                            25%
                        ,
                            4
                        ,
                            100%
                        ,
                            4
                        ,
                            100%
                        ,
,
$43029                        ,


Agricultural Technology
,
                            62
                        ,
                            3
                        ,
                            5%
                        ,
                            3
                        ,
                            100%
                        ,
,
,
,
,


Animal and Poultry Sciences
,
                            176
                        ,
                            40
                        ,
                            23%
                        ,
                            15
                        ,
                            38%
                        ,
                            7
                        ,
                            47%
                        ,
,
$29120                        ,


Applied Economic Management
,
                            36
                        ,
                            11
                        ,
                            31%
                        ,
                            4
                        ,
                            36%
                        ,
                            3
                        ,
                            75%
                        ,
,
,


Biochemistry
,
                            51
                        ,
                            11
                        ,
                            22%
                        ,
                            4
                        ,
                            36%
                        ,
                            3
                        ,
                            75%
                        ,
,
,


Crop and Soil Environmental Sciences
,
                            25
                        ,
                            5
                        ,
                            20%
                        ,
                            1
                        ,
                            20%
                        ,
                            1
                        ,
                            100%
                        ,
,
,


Dairy Science
,
                            19
                        ,
                            4
                        ,
                            21%
                        ,
,
                            0%
                        ,
,
,
,
,


Environmental Horticulture
,
                            25
                        ,
                            6
                        ,
                            24%
                        ,
                            2
                        ,
                            33%
                        ,
                            2
                        ,
                            100%
                        ,
,
,


Environmental Science
,
                            33
                        ,
                            9
                        ,
                            27%
                        ,
                            6
                        ,
                            67%
                        ,
                            4
                        ,
                            67%
                        ,
,
$45000                        ,


Food Science and Technology
,
                            25
                        ,
                            9
                        ,
                            36%
                        ,
                            4
                        ,
                            44%
                        ,
                            2
                        ,
                            50%
                        ,
,
,


Human Nutrition, Foods and Exercise
,
                            220
                        ,
                            36
                        ,
                            16%
                        ,
                            9
                        ,
                            25%
                        ,
                            4
                        ,
                            44%
                        ,
,
$47840                        ,


Landscape Horticulture and Design
,
                            3
                        ,
                            0
                        ,
                            0%
                        ,
,
,
,
,
,
,


College of Architecture and Urban Studies
,
                            405
                        ,
                            112
                        ,
                            28%
                        ,
                            77
                        ,
                            69%
                        ,
                            51
                        ,
                            66%
                        ,
$50000                        ,
$55000                        ,
$65000

Architecture
,
                            126
                        ,
                            39
                        ,
                            31%
                        ,
                            29
                        ,
                            74%
                        ,
                            17
                        ,
                            59%
                        ,
$47200                        ,
$53000                        ,
$55000

Art
,
                            50
                        ,
                            11
                        ,
                            22%
                        ,
                            5
                        ,
                            45%
                        ,
                            2
                        ,
                            40%
                        ,
,
,


Building Construction
,
                            120
                        ,
                            33
                        ,
                            28%
                        ,
                            30
                        ,
                            91%
                        ,
                            23
                        ,
                            77%
                        ,
$62000                        ,
$65000                        ,
$70000

Environmental Policy and Planning
,
                            15
                        ,
                            5
                        ,
                            33%
                        ,
                            1
                        ,
                            20%
                        ,
                            1
                        ,
                            100%
                        ,
,
,


Industrial Design
,
                            34
                        ,
                            5
                        ,
                            15%
                        ,
                            4
                        ,
                            80%
                        ,
                            2
                        ,
                            50%
                        ,
,
,


Interior Design
,
                            28
                        ,
                            13
                        ,
                            46%
                        ,
                            6
                        ,
                            46%
                        ,
                            4
                        ,
                            67%
                        ,
,
$40000                        ,


Landscape Architecture
,
                            5
                        ,
                            1
                        ,
                            20%
                        ,
                            1
                        ,
                            100%
                        ,
                            1
                        ,
                            100%
                        ,
,
,


Public and Urban Affairs
,
                            17
                        ,
                            4
                        ,
                            24%
                        ,
                            1
                        ,
                            25%
                        ,
                            1
                        ,
                            100%
                        ,
,
,


Smart and Sustainable Cities
,
                            10
                        ,
                            1
                        ,
                            10%
                        ,
,
                            0%
                        ,
,
,
,
,


College of Engineering
,
                            1843
                        ,
                            562
                        ,
                            30%
                        ,
                            417
                        ,
                            74%
                        ,
                            359
                        ,
                            86%
                        ,
$66560                        ,
$73000                        ,
$80300

Aerospace Engineering
,
                            134
                        ,
                            45
                        ,
                            34%
                        ,
                            22
                        ,
                            49%
                        ,
                            18
                        ,
                            82%
                        ,
$67735                        ,
$70072                        ,
$75000

Biological Systems Engineering
,
                            55
                        ,
                            19
                        ,
                            35%
                        ,
                            11
                        ,
                            58%
                        ,
                            8
                        ,
                            73%
                        ,
,
$65000                        ,


Chemical Engineering
,
                            111
                        ,
                            36
                        ,
                            32%
                        ,
                            25
                        ,
                            69%
                        ,
                            22
                        ,
                            88%
                        ,
$67000                        ,
$70072                        ,
$75000

Chip-Scale Integration
,
                            2
                        ,
                            0
                        ,
                            0%
                        ,
,
,
,
,
,
,


Civil Engineering
,
                            187
                        ,
                            64
                        ,
                            34%
                        ,
                            43
                        ,
                            67%
                        ,
                            33
                        ,
                            77%
                        ,
$60000                        ,
$63024                        ,
$68000

Communications & Networking
,
                            3
                        ,
                            1
                        ,
                            33%
                        ,
,
                            0%
                        ,
,
,
,
,


Computer Engineering
,
                            127
                        ,
                            43
                        ,
                            34%
                        ,
                            34
                        ,
                            79%
                        ,
                            27
                        ,
                            79%
                        ,
$72000                        ,
$77700                        ,
$90000

Computer Science
,
                            313
                        ,
                            101
                        ,
                            32%
                        ,
                            86
                        ,
                            85%
                        ,
                            79
                        ,
                            92%
                        ,
$80000                        ,
$90000                        ,
$110000

Construction Engineering and Management
,
                            22
                        ,
                            6
                        ,
                            27%
                        ,
                            6
                        ,
                            100%
                        ,
                            6
                        ,
                            100%
                        ,
,
$64000                        ,


Controls, Robotics, & Autonomy
,
                            26
                        ,
                            6
                        ,
                            23%
                        ,
                            5
                        ,
                            83%
                        ,
                            4
                        ,
                            80%
                        ,
,
$74000                        ,


Electrical Engineering
,
                            80
                        ,
                            29
                        ,
                            36%
                        ,
                            25
                        ,
                            86%
                        ,
                            19
                        ,
                            76%
                        ,
$54500                        ,
$70054                        ,
$74500

Energy & Power Electronics Systems
,
                            10
                        ,
                            3
                        ,
                            30%
                        ,
                            3
                        ,
                            100%
                        ,
                            3
                        ,
                            100%
                        ,
,
,


Engineering Science and Mechanics
,
                            27
                        ,
                            9
                        ,
                            33%
                        ,
                            5
                        ,
                            56%
                        ,
                            5
                        ,
                            100%
                        ,
,
$75000                        ,


Industrial and Systems Engineering
,
                            182
                        ,
                            54
                        ,
                            30%
                        ,
                            46
                        ,
                            85%
                        ,
                            41
                        ,
                            89%
                        ,
$68000                        ,
$72000                        ,
$78000

Machine Learning
,
                            22
                        ,
                            6
                        ,
                            27%
                        ,
                            5
                        ,
                            83%
                        ,
                            3
                        ,
                            60%
                        ,
,
,


Materials Science and Engineering
,
                            63
                        ,
                            11
                        ,
                            17%
                        ,
                            6
                        ,
                            55%
                        ,
                            6
                        ,
                            100%
                        ,
,
$67000                        ,


Mechanical Engineering
,
                            412
                        ,
                            113
                        ,
                            27%
                        ,
                            84
                        ,
                            74%
                        ,
                            74
                        ,
                            88%
                        ,
$65000                        ,
$70000                        ,
$75000

Micro/Nano Systems
,
                            3
                        ,
                            1
                        ,
                            33%
                        ,
,
                            0%
                        ,
,
,
,
,


Mining Engineering
,
                            21
                        ,
                            4
                        ,
                            19%
                        ,
                            4
                        ,
                            100%
                        ,
                            4
                        ,
                            100%
                        ,
,
$65000                        ,


Networking & Cybersecurity
,
                            12
                        ,
                            2
                        ,
                            17%
                        ,
                            2
                        ,
                            100%
                        ,
                            2
                        ,

In [53]:
column_names = ["College/Major", "Graduates","Respondents","% Respondents", "Employed", "% Employed", "Reported Salary", "% Reported Salary", "25th Percentile", "Median", "75th Percentile"]
df = pd.DataFrame(data,columns = column_names )
df = df[1:].replace({r'\s+$': '', r'^\s+': ''}, regex=True).replace(r'\n',  ' ', regex=True)
df

,College/Major,Graduates,Respondents,% Respondents,Employed,% Employed,Reported Salary,% Reported Salary,25th Percentile,Median,75th Percentile
1,Whole University,6766,2113,31%,1397,66%,1064,76%,$48500,$64000,$75000
2,College of Agriculture and Life Sciences,733,154,21%,62,40%,39,63%,$29120,$38000,$46000
3,Agribusiness,42,16,38%,10,63%,9,90%,,$40000,
4,Agricultural Sciences,16,4,25%,4,100%,4,100%,,$43029,
5,Agricultural Technology,62,3,5%,3,100%,,,,,
...,...,...,...,...,...,...,...,...,...,...,...
119,Finance,239,112,47%,98,88%,80,82%,$50000,$60000,$66000
120,Hospitality and Tourism Management,54,32,59%,28,88%,21,75%,$34008,$40000,$50000
121,Management,112,47,42%,36,77%,28,78%,$40000,$46356,$50000
122,Marketing Management,148,76,51%,59,78%,46,78%,$42000,$52000,$62500
123,Real Estate,39,18,46%,16,89%,13,81%,$47840,$50000,$56000

In [54]:
df.to_csv('salary_2019-2020.csv')

In [56]:
url = "https://fds.career.vt.edu/Salary/Details?cohort=2018-2019&dispmajor=Y"
resp= requests.get(url)
soup = bs(resp.text)
data = []
for row in soup.select('tr'):
    row_text = [x.text for x in row.find_all('td')]
    data.append(row_text)
df = pd.DataFrame(data,columns = column_names )
df = df[1:].replace({r'\s+$': '', r'^\s+': ''}, regex=True).replace(r'\n',  ' ', regex=True)
df

,College/Major,Graduates,Respondents,% Respondents,Employed,% Employed,Reported Salary,% Reported Salary,25th Percentile,Median,75th Percentile
1,Whole University,6867,3789,55%,2360,62%,1968,83%,$45000,$61800,$70000
2,College of Agriculture and Life Sciences,892,404,45%,145,36%,101,70%,$30000,$40000,$53000
3,Agribusiness,39,16,41%,12,75%,9,75%,,$35000,
4,Agricultural Sciences,13,5,38%,3,60%,2,67%,,,
5,Agricultural Technology,68,15,22%,11,73%,4,36%,,$22880,
...,...,...,...,...,...,...,...,...,...,...,...
104,Finance,282,173,61%,149,86%,135,91%,$50000,$58000,$68000
105,Hospitality and Tourism Management,62,39,63%,32,82%,26,81%,$32365,$41000,$45000
106,Management,129,79,61%,62,78%,55,89%,$40600,$50000,$63000
107,Marketing Management,163,85,52%,71,84%,63,89%,$39000,$45000,$60000
108,Real Estate,32,20,63%,18,90%,13,72%,$45000,$51000,$55000

In [57]:
df.to_csv('salary_2018-2019.csv')

In [58]:
url = "https://fds.career.vt.edu/Salary/Details?cohort=2017-2018&dispmajor=Y"
resp= requests.get(url)
soup = bs(resp.text)
data = []
for row in soup.select('tr'):
    row_text = [x.text for x in row.find_all('td')]
    data.append(row_text)
df = pd.DataFrame(data,columns = column_names )
df = df[1:].replace({r'\s+$': '', r'^\s+': ''}, regex=True).replace(r'\n',  ' ', regex=True)
df

,College/Major,Graduates,Respondents,% Respondents,Employed,% Employed,Reported Salary,% Reported Salary,25th Percentile,Median,75th Percentile
1,Whole University,5619,3901,69%,2233,57%,1891,84%,$45000,$60000,$70000
2,College of Agriculture and Life Sciences,695,442,64%,160,36%,112,70%,$30000,$40000,$47500
3,Agribusiness,37,29,78%,25,86%,20,80%,$35000,$40000,$54000
4,Agricultural Sciences,13,8,62%,5,63%,3,60%,,,
5,Agricultural Technology,35,16,46%,11,69%,7,63%,,$40000,
...,...,...,...,...,...,...,...,...,...,...,...
105,Finance,246,169,69%,145,86%,134,92%,$50000,$58500,$65000
106,Hospitality & Tourism Management,55,37,67%,33,89%,32,96%,$32000,$40000,$44000
107,Management,85,58,68%,42,72%,36,85%,$43000,$51000,$60000
108,Marketing Management,156,104,67%,88,85%,77,87%,$40000,$52000,$60000
109,Real Estate,16,11,69%,10,91%,7,70%,,$52000,

In [59]:
df.to_csv('salary_2017-2018.csv')

In [60]:
url = "https://fds.career.vt.edu/Salary/Details?cohort=2016-2017&dispmajor=Y"
resp= requests.get(url)
soup = bs(resp.text)
data = []
for row in soup.select('tr'):
    row_text = [x.text for x in row.find_all('td')]
    data.append(row_text)
df = pd.DataFrame(data,columns = column_names )
df = df[1:].replace({r'\s+$': '', r'^\s+': ''}, regex=True).replace(r'\n',  ' ', regex=True)
df

,College/Major,Graduates,Respondents,% Respondents,Employed,% Employed,Reported Salary,% Reported Salary,25th Percentile,Median,75th Percentile
1,Whole University,5660,3897,69%,2040,52%,1751,85%,$45000,$60000,$68000
2,College of Agriculture and Life Sciences,686,479,70%,131,26%,99,75%,$30000,$35000,$45250
3,Agribusiness,30,20,67%,11,55%,11,100%,,$45000,
4,Agricultural Sciences,17,13,76%,7,54%,5,71%,,$35000,
5,Agricultural Technology,44,21,48%,12,58%,7,58%,,$38000,
...,...,...,...,...,...,...,...,...,...,...,...
99,"Economics, Business",12,6,50%,3,50%,3,100%,,,
100,Finance,210,137,65%,99,73%,94,94%,$50000,$57000,$65000
101,Hospitality & Tourism Management,73,52,71%,41,79%,35,85%,$37250,$43000,$47625
102,Management,103,56,54%,37,65%,35,94%,$38965,$47500,$55500
103,Marketing Management,142,107,75%,71,66%,61,85%,$40000,$46000,$58000

In [61]:
df.to_csv('salary_2016-2017.csv')

In [62]:
url = "https://fds.career.vt.edu/Salary/Details?cohort=2015-2016&dispmajor=Y"
resp= requests.get(url)
soup = bs(resp.text)
data = []
for row in soup.select('tr'):
    row_text = [x.text for x in row.find_all('td')]
    data.append(row_text)
df = pd.DataFrame(data,columns = column_names )
df = df[1:].replace({r'\s+$': '', r'^\s+': ''}, regex=True).replace(r'\n',  ' ', regex=True)
df

,College/Major,Graduates,Respondents,% Respondents,Employed,% Employed,Reported Salary,% Reported Salary,25th Percentile,Median,75th Percentile
1,Whole University,5670,3494,62%,1751,50%,1506,86%,$43028,$58000,$66900
2,College of Agriculture and Life Sciences,710,425,60%,130,31%,103,79%,$23750,$34000,$45000
3,Agribusiness,33,18,55%,12,67%,10,83%,,$45000,
4,Agricultural Sciences,27,16,59%,9,57%,8,88%,,$30500,
5,Agricultural Technology,57,15,26%,8,54%,5,62%,,$26000,
...,...,...,...,...,...,...,...,...,...,...,...
101,"Economics, Business",19,11,58%,7,64%,7,100%,,$58000,
102,Finance,222,143,64%,95,67%,87,91%,$50750,$59000,$61250
103,Hospitality & Tourism Management,68,39,57%,31,80%,27,87%,$40000,$44000,$45575
104,Management,114,76,67%,51,67%,47,92%,$40000,$48000,$54500
105,Marketing Management,153,97,63%,67,69%,58,86%,$40000,$48000,$58000

In [63]:
df.to_csv('salary_2015-2016.csv')

In [64]:
url = "https://fds.career.vt.edu/Salary/Details?cohort=2014-2015&dispmajor=Y"
resp= requests.get(url)
soup = bs(resp.text)
data = []
for row in soup.select('tr'):
    row_text = [x.text for x in row.find_all('td')]
    data.append(row_text)
df = pd.DataFrame(data,columns = column_names )
df = df[1:].replace({r'\s+$': '', r'^\s+': ''}, regex=True).replace(r'\n',  ' ', regex=True)
df

,College/Major,Graduates,Respondents,% Respondents,Employed,% Employed,Reported Salary,% Reported Salary,25th Percentile,Median,75th Percentile
1,Whole University,5610,3274,58%,1246,38%,1017,81%,$45000,$58000,$65515
2,College of Agriculture and Life Sciences,634,336,53%,75,23%,51,68%,$32375,$40000,$45000
3,Agribusiness,20,12,60%,7,58%,6,85%,,$41000,
4,Agricultural Sciences,22,15,68%,6,40%,2,33%,,,
5,Agricultural Technology,49,12,24%,5,42%,4,80%,,$37500,
...,...,...,...,...,...,...,...,...,...,...,...
95,"Economics, Business",34,22,65%,11,50%,10,90%,,$59000,
96,Finance,207,129,62%,81,63%,69,85%,$50000,$57000,$60000
97,Hospitality & Tourism Management,75,45,60%,26,60%,22,84%,$34750,$43000,$46000
98,Management,110,64,58%,36,57%,31,86%,$43042,$50000,$60000
99,Marketing Management,156,81,52%,49,60%,42,85%,$34500,$43000,$50000

In [65]:
df.to_csv('salary_2014-2015.csv')